Repository grafana/tempo, pull requests merged in 2022-05, with the labels that each got.

#1371 Refactor for alternative block formats 3
  cmd/tempo-cli/cmd-gen-bloom.go
  cmd/tempo-cli/cmd-gen-index.go
  cmd/tempo-cli/cmd-list-block.go
  cmd/tempo-cli/cmd-list-index.go
  cmd/tempo-cli/cmd-query-blocks.go
  cmd/tempo-cli/cmd-search.go
  cmd/tempo-cli/cmd-view-index.go
  cmd/tempo-serverless/handler.go
  modules/ingester/instance.go
  modules/ingester/instance_search_test.go
  tempodb/backend/block_meta.go
  tempodb/compactor_test.go
  tempodb/encoding/common/interfaces.go
  tempodb/encoding/v2/backend_block.go
  tempodb/encoding/v2/compactor.go
  tempodb/encoding/v2/create_block.go
  tempodb/encoding/v2/encoding.go
  tempodb/encoding/v2/iterator.go
  tempodb/encoding/v2/iterator_deduping.go
  tempodb/encoding/v2/iterator_multiblock.go
  tempodb/encoding/v2/iterator_multiblock_test.go
  tempodb/encoding/v2/iterator_paged.go
  tempodb/encoding/v2/iterator_paged_test.go
  tempodb/encoding/v2/iterator_prefetch.go
  tempodb/encoding/v2/iterator_record.go
  tempodb/encoding/v2/streaming_block.go
  tempodb/encoding/v2/streaming_block_test.go
  tempodb/encoding/versioned.go
  tempodb/encoding/versioned_test.go
  tempodb/retention_test.go
  tempodb/search/backend_search_block.go
  tempodb/search/backend_search_block_test.go
  tempodb/search/backend_search_block_writer.go
  tempodb/search/rescan_blocks.go
  tempodb/search/streaming_search_block.go
  tempodb/search/streaming_search_block_test.go
  tempodb/tempodb.go
  tempodb/tempodb_test.go
  tempodb/wal/append_block.go
  tempodb/wal/local_block.go
  tempodb/wal/replay.go
  tempodb/wal/wal.go
  tempodb/wal/wal_test.go
Labels: refactor

#1422 distributor: prevent panics when concurrently calling to forwarder's…
  CHANGELOG.md
  integration/bench/load_test.go
  modules/distributor/forwarder.go
Labels: backport r41

#1451 Publish compiled mixin like mimir
  docs/tempo/website/operations/monitoring.md
  operations/tempo-mixin-compiled/alerts.yaml
  operations/tempo-mixin-compiled/dashboards/tempo-operational.json
  operations/tempo-mixin-compiled/dashboards/tempo-reads.json
  operations/tempo-mixin-compiled/dashboards/tempo-resources.json
  operations/tempo-mixin-compiled/dashboards/tempo-writes.json
  operations/tempo-mixin-compiled/rules.yaml
  operations/tempo-mixin/Makefile
Labels: ease-of-use
